spring:
  datasource:
    hikari.schema: public
    url: jdbc:postgresql://localhost:5432/project_management_ipf?serverTimezone=UTC
    username: postgres
    password:
  #Email service
  mail:
    host: smtp.gmail.com
    username:
    password:
    properties:
      mail:
        transport.protocol: smtp
        smtp:
          port: 587
          auth: true
          starttls.enable: true
  #          ssl.enable: true

